services:
  - type: web
    name: fcm-push-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json
